
on : 
push : 
branches:
-master






jobs :
build :
runs-on : ubinto-lastest
steps :
  - usres : action/checkout@v3
  -name: "login to docker hub"
  run: dockerlogin --username ${{ secrets.docker-USERNAME}} --password ${{DOCKERTOKEN}}  
  
